### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by ghost** [sderaut/obmenux#1]
i have no idea what i'm doing. i tried setting up git, that's beyond me. downloaded the zip. extracted to a directory (obmenux-what) and in that directory, i followed the README instructions.

nope.

[a@i obmenux-what]$ ls
COPYING  minisetup.py  obmenu.glade  obxml.py  pipes-help  setup.py
icons    obmenu        obxml-help    pipes     README
[a@i obmenux-what]$ su
Password: 
[root@i obmenux-what]# python setup.py install
running install
running build
running build_py
creating build
creating build/lib
copying obxml.py -> build/lib
running build_scripts
creating build/scripts-3.4
copying and adjusting obmenu -> build/scripts-3.4
copying and adjusting pipes/obm-xdg -> build/scripts-3.4
copying and adjusting pipes/obm-dir -> build/scripts-3.4
copying and adjusting pipes/obm-moz -> build/scripts-3.4
copying and adjusting pipes/obm-nav -> build/scripts-3.4
changing mode of build/scripts-3.4/obmenu from 644 to 755
changing mode of build/scripts-3.4/obm-xdg from 644 to 755
changing mode of build/scripts-3.4/obm-dir from 644 to 755
changing mode of build/scripts-3.4/obm-moz from 644 to 755
changing mode of build/scripts-3.4/obm-nav from 644 to 755
running install_lib
copying build/lib/obxml.py -> /usr/lib/python3.4/site-packages
byte-compiling /usr/lib/python3.4/site-packages/obxml.py to obxml.cpython-34.pyc
  File "/usr/lib/python3.4/site-packages/obxml.py", line 118
    print "warning fake number ", n, " for ", menu, " number ", num
                               ^
SyntaxError: Missing parentheses in call to 'print'

running install_scripts
copying build/scripts-3.4/obm-dir -> /usr/bin
copying build/scripts-3.4/obmenu -> /usr/bin
copying build/scripts-3.4/obm-nav -> /usr/bin
copying build/scripts-3.4/obm-moz -> /usr/bin
copying build/scripts-3.4/obm-xdg -> /usr/bin
changing mode of /usr/bin/obm-dir to 755
changing mode of /usr/bin/obmenu to 755
changing mode of /usr/bin/obm-nav to 755
changing mode of /usr/bin/obm-moz to 755
changing mode of /usr/bin/obm-xdg to 755
running install_data
creating /usr/share/obmenu
copying obmenu.glade -> /usr/share/obmenu
copying icons/mnu16.png -> /usr/share/obmenu
copying icons/mnu48.png -> /usr/share/obmenu
running install_egg_info
Writing /usr/lib/python3.4/site-packages/obMenu-1.0-py3.4.egg-info
[root@i obmenux-what]# obmenux
bash: obmenux: command not found
[root@i obmenux-what]# obmenu
  File "/usr/bin/obmenu", line 61
    def _change_id(self, model, path, it,(old_id, new_id)):
                                         ^
SyntaxError: invalid syntax
[root@i obmenux-what]#

**Comment by ghost** [comment]
by the way, i un-installed "obmenu" before i did any of this.

**Comment by sderaut** [comment]
The problem is you're trying to build for Python 3.4. Try Python 2 by
# python2 setup.py install
No guarantees.

**Comment by ghost** [comment]
ok it worked, thx

**Comment by sderaut** [comment]
I added shebangs and changed the instructions so that users will only compile or run this version using Python 2.
