### ISSUE TITLE
items out of order in actual menu vs obmenux program

### ISSUE THREAD

**Issue by ghost** [sderaut/obmenux#2]
![switchy-menu](https://cloud.githubusercontent.com/assets/11820866/9782394/8eb07d54-5751-11e5-9930-431db950ccca.png)

reproduction (hopefully):
1. create a new menu.
2. put 4-5 things in it.
3. move something out of that menu (below lowest thing, as low as it can go, so it doesn't appear in the menu, i don't know if this step is necessary)
4. move things around in the menu. (i don't know if this step is necessary either)

save. compare with actual menu.

**Comment by sderaut** [comment]
I'm also finding things out of order in the view compared with the XML it generates. I'll have to review all the code and fix that, in order for this fork to get past being an alpha version.

**Comment by sderaut** [comment]
Please try to reproduce the bug again after downloading and installing again. (It has probably been fixed by commit 29da67e85f991e1d4bc2fbb206212b1f0d543a97.)

**Comment by cubetronic** [comment]
increment the version number every single time you change anything that 
will be included in the "zip download".

even, and especially, if it's a minor change. feel free to increment the 
patch number every time. so far i think there have been 3 versions at 1.1.1

if you get to 1.1.99, that's cool.

**Comment by ghost** [comment]
i've tested obmenux 1.1.1, and i can't reproduce this bug anymore.

i'm ok with this issue being closed.

**Comment by sderaut** [comment]
Thanks. Closing issue.
