### ISSUE TITLE
obmenux won't start

### ISSUE THREAD

**Issue by ghost** [sderaut/obmenux#4]
```
[a@i obmenux-1.1.1]$ obmenux
  File "/usr/bin/obmenux", line 750
    elif os.path.isfile(homegladepath)
                                     ^
SyntaxError: invalid syntax
```

**Comment by ghost** [comment]
error from commit: 709f0e808e8a18f850cc0ec469959bfe21f4ebe4

**Comment by ghost** [comment]
whoops.. i was just trying to cancel my comment.. i was gonna say.. i hope i don't <i>have to</i> do a user-specific install

**Comment by sderaut** [comment]
Sorry, I should have tested that edit before making a commit or pushing to GitHub. My mistake.

No, you don't have to do a user-specific install, it's just an extra feature that GLolol/obmenu had a commit for, except his was in the wrong priority, to ignore the ~/.local/share if there's something in /usr/local/share or /usr/share so I thought I'd redo it and do it better. Pride goes before a fall.

**Comment by sderaut** [comment]
Added the missing colon to fix "invalid syntax" and tested install. Closing issue.
